name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  buildimage:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Execute python tests
        run: |
          pwd
          cd ./python 
          #python -m pip install --upgrade pip
          python install -r requirements.txt
          python tests.py -v

      - name: build the docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: virenpatel/sretool:0.1.0



